FoodProject/FoodProject/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foodApp.urls')),
    path('register/', users_views.register, name='register'),
    path('login/',auth_view.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',users_views.profilePage,name='profile'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FoodProject/foodApp/urls.py
from django.urls import path
from foodApp import views

# namespacing
app_name = 'foodApp'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('detail/<int:pk>/',views.ItemDetail.as_view(),name='detail'),
    # Add Item
    path('create/', views.CreateItem.as_view(), name='create_item'),
    # edit/1
    path('update/<int:id>/',views.update_item,name='update'),
    # delete
    path('delete/<int:id>/',views.delete_item,name='delete')

]

FoodProject/foodApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://media.istockphoto.com/id/1137255480/vector/coming-soon-sign.jpg?s=1024x1024&w=is&k=20&c=6ey80gBK_vWoOHJSNzeNL1KXVCGHevn1bXTsafUF0U4=")

    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("foodApp:detail", kwargs={'pk':self.pk})
    
    

FoodProject/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

FoodProject/foodApp/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
    

FoodProject/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        

FoodProject/foodApp/views.py
from django.forms import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.views import generic

def index(request):
    item_list = Item.objects.all()
    return render(request,'foodApp/index.html',{'item_list':item_list})

class IndexView(generic.ListView):
    model = Item
    template_name = 'foodApp/index.html'
    context_object_name = 'item_list'

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {'item':item}
    return render(request,'foodApp/detail.html', context)

class ItemDetail(generic.DeleteView):
    model = Item
    template_name = 'foodApp/detail.html'

def create_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('foodApp:index')
            # return HttpResponse("Item added Successfully")
        
    form = ItemForm()
    return render(request, 'foodApp/create.html',{'form':form})

class CreateItem(generic.edit.CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'foodApp/create.html'

    def form_invalid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form  = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('foodApp:index')
    return render(request,'foodApp/create.html',{'form':form, 'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('foodApp:index')
    return render(request,'foodApp/delete.html',{'item':item})

FoodProject/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created')
            return redirect('login')
        
    form = RegisterForm()
    return render(request, 'users/register.html',{'form':form}) 

@login_required
def profilePage(request):
    return render(request,'users/profile.html')

FoodProject/foodApp/templates/foodApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'foodApp/style.css' %}"></link>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar">
         <a class="nav-item nav-link" href="#">ViewItem</a>
         <a class="nav-item nav-link" href="{% url 'foodApp:create_item' %}">AddItem</a>
         <a class="nav-item nav-link" href="#">DeleteItem</a>
         {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
         {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
         {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}  {% endblock %}  
</body>
</html>

FoodProject/foodApp/templates/foodApp/create.html
{% extends 'foodApp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title offset-md-4">Add Item</div>
                </div>
                <div class="card-body">
                    <form method="post" class="offset-md-2">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <button class="btn-info offset-md-2" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}



   

FoodProject/foodApp/templates/foodApp/delete.html
<form method="post">
    {% csrf_token %}
    <h3>Are you sure to delete this {{ item.item_name }}</h3>
    <button type="submit">Confirm</button>
</form>

FoodProject/foodApp/templates/foodApp/detail.html
{% extends 'foodApp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ object.item_image }}" />
        </div>
        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>${{ object.item_price }}</h3>
            <a href="{% url 'foodApp:delete' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}  

FoodProject/foodApp/templates/foodApp/index.html
{% extends 'foodApp/base.html' %}

{% block body %}
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4">
                <h2>{{ item.item_name }}</h2>
                <h3>{{ item.item_desc }}</h3>
                <h4>₹{{ item.item_price }}</h4>
                <h5>{{item.user_name}}</h5>

            </div>
            <div class="col-md-2">
                <a href="{% url 'foodApp:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}
    {% endblock %}  
    <!-- This is old code -->
        <ul>
            <li>
                <a href="{% url 'foodApp:detail' qs.id %}">
                    {{qs.id}}
                    {{qs.item_name}}
                </a>
            </li>
        </ul>
 

FoodProject/users/templates/users/login.html
{% extends 'foodApp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">Login</div>
                </div>
                <div class="card-body">
                    <form method="post" class="offset-md-2">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <br>
                        <button class="btn-info offset-md-2" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

FoodProject/users/templates/users/logout.html
<h1>You are successfully logged out</h1>

FoodProject/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img height="300" width="200" src="{{ user.profile.image.url }}" />

FoodProject/users/templates/users/register.html
{% extends 'foodApp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title offset-md-4">Register</div>
                </div>
                <div class="card-body">
                    <form method="post" class="offset-md-2">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{field.name}}
                                <br>
                                {{field}}
                            </div>
                        {% endfor %}
                        <br>
                        <button class="btn-info offset-md-2" type="submit">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}



   